daemon:
  interval_seconds: 20
  log_path: "../logs/daemon.log"
  error_log_path: "../logs/daemon_error.log"

filters:
  images:
    - "low"
    - "cpu_high"
    - "ram_high"
  names: []

http:
  enabled: true
  addr: "0.0.0.0:8080"
